#!/bin/bash

ACTIVE_WORKSPACE=$(hyprctl activeworkspace -j | jq -r '.id')
CURRENT_LAYOUT=$(hyprctl activeworkspace -j | jq -r '.tiledLayout')

case "$CURRENT_LAYOUT" in
  dwindle) NEW_LAYOUT=master ;;
  master) NEW_LAYOUT=scrolling ;;
  scrolling) NEW_LAYOUT=monocle ;;
  monocle) NEW_LAYOUT=dwindle ;;
  *) NEW_LAYOUT=dwindle ;;
esac

hyprctl keyword workspace "$ACTIVE_WORKSPACE, layout:$NEW_LAYOUT"
notify-send -u low "Workspace layout set to $NEW_LAYOUT"
